services:
  bff-workstation:
    build:
      context: ..
      dockerfile: backend/src/apps/Nexus.Bff/Dockerfile
    image: nexus/bff:1.0.0 

  auth-api:
    build:
      context: ..
      dockerfile: backend/src/services/Authentication/Nexus.Authentication.Service.Api/Dockerfile
    image: nexus/auth-api:1.0.0

  user-management-api:
    build:
      context: ..
      dockerfile: backend/src/services/UserManagement/Nexus.UserManagement.Service.Api/Dockerfile
    image: nexus/user-management-api:1.0.0

  nexus-ui:
    build:
      context: ../web/nexus-ui   
      dockerfile: Dockerfile
    image: nexus/ui:1.0.0